### ISSUE TITLE
Atomic CSS??

### ISSUE THREAD

**Issue by benfrain** [chantastic/minions.css#31]
Not sure why you reference other libraries but not the 'Daddy' of Atomic CSS: https://www.smashingmagazine.com/2013/10/challenging-css-best-practices-atomic-approach/

Atomic CSS at http://acss.io should be the number one reference for all of these atomic libraries.

**Comment by chantastic** [comment]
This popped up in my Twitter feed yesterday. I attempted to clarify there. https://twitter.com/chantastic/status/791759388029677569

I credited the libraries that I researched and that inspired me to develop a clearer set of naming rules around the practice of CSS classes.

This is different from ACSS in it's current form because it embraces the constraints. Obviously you can't write classes for every color, width, and media-query. When embraced, those constraints become a design system.

As I mentioned to the author of that post, I can't credit something I haven't read. While I have read the intro to acss.io, everything pointed to Atomizer (at the time that I read it). This is a much different philosophy than a constrained set of CSS classes. If I had felt it relevant, I would have included it.

Is there a place in the repo that I specifically reference "Atomic CSS", outside of the outdated description for Tachyons? If so, I'll correct the error my removing the reference.

This library and approach bear no similarity to the contemporary ACSS library. If this approach was part of ACSS's history, that blog post is the only public link. As I mentioned, it made no direct contribution to my work. I can't give attribution to something I didn't read or learn from.

**Comment by chantastic** [comment]
Feel free to re-open if you have additional comments on the matter.
